image: gcc

default:
  before_script:
    - apt update && apt -y install cmake libcunit1-dev


build_job:
  stage: build
  script:
    - pwd
    - git status
    - mkdir BuildCI
    - cd BuildCI
    - cmake ..

build_job:
  stage: build
  script:
    - pwd
    - git status
    - cmake --build .
    - ctest -V
