image: gcc

stages:
 - build
 - test 


default:
  before_script:
    - apt update && apt -y install cmake libcunit1-dev

building_job:
  stage: build
  script:
    - pwd
    - git status
    - mkdir BuildCI
    - cd BuildCI
    - cmake ..

testing_job:
  stage: test
  script:
    - pwd
    - git status
    - ctest -V
