image: gcc

build_cunit:
  stage: build
  before_script:
     - apt update && apt -y install cmake libcunit1-dev
  script:
    - mkdir BuildCI
    - cd BuildCI
    - cmake --version 
    - gcc --version
    - cmake ..
    - cmake --build .
  script:
    - ctest -V
