image: gcc

stages:
 - build
 - test
 - coverage

default:
  before_script:
    - apt update && apt -y install cmake libcunit1-dev gcovr

building_test:
  stage: build
  script:
    - mkdir BuildCI
    - cd BuildCI
    - cmake ..
    - cmake --build . --target test_pract1
  artifacts:
    paths:
    - BuildCI

testing_job:
  stage: test
  script:
    - cd BuildCI
    - ctest -V

computing_coverage:
  stage: coverage
  script:
    - mkdir Coverage
    - cd BuildCI
    - cmake --build . --target cover_html
  artifacts:
    paths:
    - BuildCI/Coverage
