image: gcc

stages:
 - build
 - test 


default:
  before_script:
    - apt update && apt -y install cmake libcunit1-dev

building_test:
  stage: build
  script:
    - mkdir BuildCI
    - cd BuildCI
    - cmake ..
    - cmake --build . --target test_pract1
  artifacts:
    paths:
    - BuildCI

building_app:
  stage: build
  script:
    - mkdir BuildApp
    - cd BuildApp
    - cmake ..
    - cmake --build . --target app
  artifacts:
    paths:
    - BuildApp

testing_job:
  stage: test
  script:
    - cd BuildCI
    - ctest -V
