image: gcc

pipelines:
  default:
    - step:
        script: 
        - apt update && apt -y install cmake libcunit1-dev gcovr
        - mkdir BuildCI
        - cd BuildCI
        - cmake ..
        - cmake --build . --target test_pract1
        artifacts:
        - BuildCI/**
    - step:
        script: 
        - apt update && apt -y install cmake libcunit1-dev gcovr
        - cd BuildCI
        - ctest -V
    - step:
        script:
        - apt update && apt -y install cmake libcunit1-dev gcovr
        - mkdir Coverage
        - cd BuildCI
        - cmake --build . --target cover_html
        artifacts:
        - BuildCI/Coverage/**