#image: gcc
image: sylv1thery/imgdev

pipelines:
  default:
    - step:
        name: building
        script: 
#        - apt update && apt -y install cmake libcunit1-dev gcovr
        - mkdir BuildCI
        - cd BuildCI
        - cmake ..
        - cmake --build . --target test_pract1
        artifacts:
        - BuildCI/**
    - step:
        name: testing
        script: 
 #       - apt update && apt -y install cmake libcunit1-dev gcovr
        - cd BuildCI
        - ctest -V
    - step:
        name: coverage
        script:
  #      - apt update && apt -y install cmake libcunit1-dev gcovr
        - cd BuildCI
        - mkdir Coverage
        - cmake --build . --target cover