# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc

pipelines:
  default:
    - step:
        script: 
        - apt update && apt -y install cmake libcunit1-dev gcovr
    - step:
        script: 
        - mkdir BuildCI
        - cd BuildCI
        - cmake ..
        - cmake --build . --target test_pract1
        artifacts:
        - BuildCI
    - step:
        script: 
        - mkdir BuildCI
        - cd BuildCI
        - ctest -V
    - step:
        script:
        - mkdir Coverage
        - cd BuildCI
        - cmake --build . --target cover_html
        artifacts:
        - BuildCI/Coverage