name: 'CI'

on:
  push:
    branches: 
    - master 

jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: |
        sudo apt update
        sudo apt install libcunit1-dev
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - name: 'Testing'   
      run: ctest -V
