name: 'CI'

on:
  push:
    branches: 
    - master 

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: |
        sudo apt update
        sudo apt install libcunit1-dev
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: BuildCI/
  
  test_linux:
    runs-on: ubuntu-latest
    needs: build_linux
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binaries
          path: BuildCI/
      - name: 'Testing'
        run: |
          cd BuildCI   
          ctest -V

  cover_linux:
    runs-on: ubuntu-latest
    needs: test_linux
    steps:
      - uses: actions/dowload-artifact@v2
        with:
          name: binaries
          path: BuildCI/
      - name: 'Testing'
        run: |
          cd BuildCI   
          ctest -V                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
      - uses: actions/dowload-artifact@v1
        with:
          name: binaries
          path: BuildCI/